name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:buster
    env:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
      DB_PORT: 5432
      POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
      MNEMONIC: ${{ secrets.MNEMONIC }}
      CREATIFY_CONTRACT_ADDRESS: ${{ secrets.CREATIFY_CONTRACT_ADDRESS }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      IPFS_NODE_URL: ${{ secrets.IPFS_NODE_URL }}
      CREATOR_EULA: TODO CREATOR EULA
      AUTH_EULA: TODO AUTH EULA
      LOG_TO_FILE: false
      SIGNED_BY: "LazarusNetwork"
      ALLOWED_WALLET_ADDRESS: "*"
      ORG_NAME: MyriadFlow
      HOME_TITLE: Collect And Trade The New Fresh Thing
      HOME_DESCRIPTION: A NFT marketplace to explore the digital gold mine, that supports the creators. A place where you can Make Collect and Sell digital arts.
      GRAPH_URL: https://query.graph.lazarus.network/subgraphs/name/MyriadFlow
      MARKETPLACE_CONTRACT_ADDRESS: "0x899dEf33857C491Ce61346f6e95b3a5Ee4acd24a"
      TOP_HIGHLIGHTS: 54,34,65
      TRENDINGS: 54,34,34
      TOP_BIDS: 25,65,34
      FOOTER: "MyriadFlow | Copyright © 2022 Lazarus Network Inc. All Rights Reserved."
      JWT_EXPIRATION: 48h
      APP_NAME: myriad-flow-gateway
      GIN_MODE: test
      ALLOWED_ORIGIN: "*"
      APP_PORT: 3000

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Build
        run: go build -v ./...
      - name: Test
        run: gotestsum -- -coverprofile=cover.out ./...
